# Complete network configuration
# Updated on Fri Dec 27 2025
#
# enp3s0: Bridged to br1 with static IP 192.168.3.100/24 (no gateway)
# br0: Bridge for VM networking (using eno1) with static IP 10.168.1.101/24

network:
  version: 2
  renderer: networkd
  
  ethernets:
    enp3s0:
      dhcp4: no
      dhcp6: no
    
    eno1:
      dhcp4: no
      dhcp6: no
  
  bridges:
    br0:
      interfaces: [eno1]
      dhcp4: no
      dhcp6: no
      addresses:
        - 10.168.1.101/24
      routes:
        - to: default
          via: 10.168.1.1
          metric: 100
      nameservers:
        addresses:
          - 8.8.8.8
          - 8.8.4.4
          - 10.168.1.1
      parameters:
        stp: false
        forward-delay: 0
    
    br1:
      interfaces: [enp3s0]
      dhcp4: no
      dhcp6: no
      addresses:
        - 192.168.3.100/24
      parameters:
        stp: false
        forward-delay: 0