network:
  version: 2
  renderer: networkd
  ethernets:
    # Primary network interface
    enp1s0:
      addresses:
        - 10.168.1.56/24
      routes:
        - to: default
          via: 10.168.1.1
      nameservers:
        addresses:
          - 8.8.8.8
          - 8.8.4.4
    # Secondary network interface
    enp7s0:
      addresses:
        - 192.168.3.56/24
